services:
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"

  autenticacion:
    build: ./autentificacion
    container_name: autenticacion
    ports:
      - "8002:8000"

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword123
      POSTGRES_DB: cms_db
    ports:
      - "5432:5432"

  crud:
    build: ./crud
    container_name: crud
    ports:
      - "8003:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:mysecretpassword123@db:5432/cms_db

